from flask import Flask, jsonify, request
from flask_cors import CORS
from collections import OrderedDict
import csv

app = Flask(__name__)
CORS(app)

# Using 'ID' as the unique key for the dictionary


BACKUP_INVENTORY = [
    {"id": 1, "item": "Bananas", "store": "Kroger", "price": 60.0, "stock": 0},
    {"id": 2, "item": "Apples", "store": "Kroger", "price": 29.0, "stock": 40},
    {"id": 3, "item": "Oranges", "store": "Kroger", "price": 44.0, "stock": 40},
    {"id": 4, "item": "Mandarins", "store": "Kroger", "price": 52.0, "stock": 37},
    {"id": 5, "item": "Grapes", "store": "Kroger", "price": 12.0, "stock": 43},
    {"id": 6, "item": "Strawberries", "store": "Kroger", "price": 35.0, "stock": 55},
    {"id": 7, "item": "Blueberries", "store": "Kroger", "price": 46.0, "stock": 80},
    {"id": 8, "item": "Raspberries", "store": "Kroger", "price": 33.0, "stock": 14},
    {"id": 9, "item": "Blackberries", "store": "Kroger", "price": 29.0, "stock": 44},
    {"id": 10, "item": "Watermelon", "store": "Kroger", "price": 16.0, "stock": 10},
    {"id": 11, "item": "Cantaloupe", "store": "Kroger", "price": 22.0, "stock": 15},
    {"id": 12, "item": "Honeydew melon", "store": "Kroger", "price": 37.0, "stock": 84},
    {"id": 13, "item": "Pineapple", "store": "Kroger", "price": 26.0, "stock": 18},
    {"id": 14, "item": "Lemons", "store": "Kroger", "price": 15.0, "stock": 20},
    {"id": 15, "item": "Limes", "store": "Kroger", "price": 58.0, "stock": 21},
    {"id": 16, "item": "Avocados", "store": "Kroger", "price": 12.0, "stock": 26},
    {"id": 17, "item": "Tomatoes", "store": "Kroger", "price": 64.0, "stock": 61},
    {"id": 18, "item": "Potatoes", "store": "Kroger", "price": 60.0, "stock": 26},
    {"id": 19, "item": "Sweet potatoes", "store": "Kroger", "price": 27.0, "stock": 54},
    {"id": 20, "item": "Onions", "store": "Kroger", "price": 63.0, "stock": 74},
    {"id": 21, "item": "Garlic bulbs", "store": "Kroger", "price": 50.0, "stock": 27},
    {"id": 22, "item": "Bell peppers", "store": "Kroger", "price": 19.0, "stock": 66},
    {"id": 23, "item": "Jalapeño peppers", "store": "Kroger", "price": 41.0, "stock": 70},
    {"id": 24, "item": "Cucumbers", "store": "Kroger", "price": 7.0, "stock": 42},
    {"id": 25, "item": "Zucchini", "store": "Kroger", "price": 44.0, "stock": 20},
    {"id": 26, "item": "Yellow squash", "store": "Kroger", "price": 20.0, "stock": 51},
    {"id": 27, "item": "Broccoli", "store": "Kroger", "price": 60.0, "stock": 34},
    {"id": 28, "item": "Cauliflower", "store": "Kroger", "price": 60.0, "stock": 15},
    {"id": 29, "item": "Carrots", "store": "Kroger", "price": 28.0, "stock": 22},
    {"id": 30, "item": "Baby carrots", "store": "Kroger", "price": 63.0, "stock": 75},
    {"id": 31, "item": "Celery", "store": "Kroger", "price": 22.0, "stock": 13},
    {"id": 32, "item": "Lettuce", "store": "Kroger", "price": 53.0, "stock": 56},
    {"id": 33, "item": "Spinach", "store": "Kroger", "price": 52.0, "stock": 49},
    {"id": 34, "item": "Kale", "store": "Kroger", "price": 60.0, "stock": 27},
    {"id": 35, "item": "Cabbage", "store": "Kroger", "price": 18.0, "stock": 75},
    {"id": 36, "item": "Chicken", "store": "Kroger", "price": 59.0, "stock": 41},
    {"id": 37, "item": "Ground beef", "store": "Kroger", "price": 7.0, "stock": 58},
    {"id": 38, "item": "Steak", "store": "Kroger", "price": 54.0, "stock": 99},
    {"id": 39, "item": "Pork", "store": "Kroger", "price": 37.0, "stock": 93},
    {"id": 40, "item": "Bacon", "store": "Kroger", "price": 16.0, "stock": 80},
    {"id": 41, "item": "Breakfast sausage", "store": "Kroger", "price": 51.0, "stock": 80},
    {"id": 42, "item": "Hot dogs", "store": "Kroger", "price": 29.0, "stock": 21},
    {"id": 43, "item": "Ham", "store": "Kroger", "price": 21.0, "stock": 84},
    {"id": 44, "item": "Turkey", "store": "Kroger", "price": 5.0, "stock": 82},
    {"id": 45, "item": "Salami", "store": "Kroger", "price": 67.0, "stock": 63},
    {"id": 46, "item": "Pepperoni", "store": "Kroger", "price": 61.0, "stock": 95},
    {"id": 47, "item": "Frozen chicken nuggets", "store": "Kroger", "price": 16.0, "stock": 49},
    {"id": 48, "item": "Frozen chicken tenders", "store": "Kroger", "price": 51.0, "stock": 31},
    {"id": 49, "item": "Frozen hamburger patties", "store": "Kroger", "price": 1.0, "stock": 63},
    {"id": 50, "item": "Frozen meatballs", "store": "Kroger", "price": 53.0, "stock": 98},
    {"id": 51, "item": "Bananas", "store": "Meijer", "price": 28.0, "stock": 57},
    {"id": 52, "item": "Apples", "store": "Meijer", "price": 49.0, "stock": 0},
    {"id": 53, "item": "Oranges", "store": "Meijer", "price": 49.0, "stock": 13},
    {"id": 54, "item": "Mandarins", "store": "Meijer", "price": 41.0, "stock": 57},
    {"id": 55, "item": "Grapes", "store": "Meijer", "price": 3.0, "stock": 70},
    {"id": 56, "item": "Strawberries", "store": "Meijer", "price": 20.0, "stock": 70},
    {"id": 57, "item": "Blueberries", "store": "Meijer", "price": 37.0, "stock": 69},
    {"id": 58, "item": "Raspberries", "store": "Meijer", "price": 7.0, "stock": 41},
    {"id": 59, "item": "Blackberries", "store": "Meijer", "price": 60.0, "stock": 41},
    {"id": 60, "item": "Watermelon", "store": "Meijer", "price": 1.0, "stock": 70},
    {"id": 61, "item": "Cantaloupe", "store": "Meijer", "price": 33.0, "stock": 93},
    {"id": 62, "item": "Honeydew melon", "store": "Meijer", "price": 21.0, "stock": 0},
    {"id": 63, "item": "Pineapple", "store": "Meijer", "price": 39.0, "stock": 1},
    {"id": 64, "item": "Lemons", "store": "Meijer", "price": 38.0, "stock": 15},
    {"id": 65, "item": "Limes", "store": "Meijer", "price": 49.0, "stock": 42},
    {"id": 66, "item": "Avocados", "store": "Meijer", "price": 3.0, "stock": 88},
    {"id": 67, "item": "Tomatoes", "store": "Meijer", "price": 16.0, "stock": 8},
    {"id": 68, "item": "Potatoes", "store": "Meijer", "price": 38.0, "stock": 27},
    {"id": 69, "item": "Sweet potatoes", "store": "Meijer", "price": 4.0, "stock": 43},
    {"id": 70, "item": "Onions", "store": "Meijer", "price": 41.0, "stock": 64},
    {"id": 71, "item": "Garlic bulbs", "store": "Meijer", "price": 6.0, "stock": 43},
    {"id": 72, "item": "Bell peppers", "store": "Meijer", "price": 29.0, "stock": 38},
    {"id": 73, "item": "Jalapeño peppers", "store": "Meijer", "price": 45.0, "stock": 35},
    {"id": 74, "item": "Cucumbers", "store": "Meijer", "price": 52.0, "stock": 89},
    {"id": 75, "item": "Zucchini", "store": "Meijer", "price": 56.0, "stock": 99},
    {"id": 76, "item": "Yellow squash", "store": "Meijer", "price": 42.0, "stock": 43},
    {"id": 77, "item": "Broccoli", "store": "Meijer", "price": 35.0, "stock": 31},
    {"id": 78, "item": "Cauliflower", "store": "Meijer", "price": 41.0, "stock": 8},
    {"id": 79, "item": "Carrots", "store": "Meijer", "price": 53.0, "stock": 57},
    {"id": 80, "item": "Baby carrots", "store": "Meijer", "price": 20.0, "stock": 73},
    {"id": 81, "item": "Celery", "store": "Meijer", "price": 55.0, "stock": 0},
    {"id": 82, "item": "Lettuce", "store": "Meijer", "price": 55.0, "stock": 34},
    {"id": 83, "item": "Spinach", "store": "Meijer", "price": 38.0, "stock": 84},
    {"id": 84, "item": "Kale", "store": "Meijer", "price": 7.0, "stock": 32},
    {"id": 85, "item": "Cabbage", "store": "Meijer", "price": 35.0, "stock": 20},
    {"id": 86, "item": "Chicken", "store": "Meijer", "price": 4.0, "stock": 65},
    {"id": 87, "item": "Ground beef", "store": "Meijer", "price": 40.0, "stock": 65},
    {"id": 88, "item": "Steak", "store": "Meijer", "price": 27.0, "stock": 66},
    {"id": 89, "item": "Pork", "store": "Meijer", "price": 54.0, "stock": 87},
    {"id": 90, "item": "Bacon", "store": "Meijer", "price": 54.0, "stock": 51},
    {"id": 91, "item": "Breakfast sausage", "store": "Meijer", "price": 47.0, "stock": 54},
    {"id": 92, "item": "Hot dogs", "store": "Meijer", "price": 1.0, "stock": 40},
    {"id": 93, "item": "Ham", "store": "Meijer", "price": 63.0, "stock": 44},
    {"id": 94, "item": "Turkey", "store": "Meijer", "price": 6.0, "stock": 0},
    {"id": 95, "item": "Salami", "store": "Meijer", "price": 41.0, "stock": 58},
    {"id": 96, "item": "Pepperoni", "store": "Meijer", "price": 51.0, "stock": 34},
    {"id": 97, "item": "Frozen chicken nuggets", "store": "Meijer", "price": 20.0, "stock": 80},
    {"id": 168, "item": "Bananas", "store": "Sam's Club", "price": 25.0, "stock": 21},
    {"id": 169, "item": "Apples", "store": "Sam's Club", "price": 4.0, "stock": 55},
    {"id": 170, "item": "Oranges", "store": "Sam's Club", "price": 66.0, "stock": 7},
    {"id": 171, "item": "Mandarins", "store": "Sam's Club", "price": 61.0, "stock": 0},
    {"id": 172, "item": "Grapes", "store": "Sam's Club", "price": 32.0, "stock": 49},
    {"id": 173, "item": "Strawberries", "store": "Sam's Club", "price": 20.0, "stock": 55},
    {"id": 174, "item": "Blueberries", "store": "Sam's Club", "price": 46.0, "stock": 45},
    {"id": 175, "item": "Raspberries", "store": "Sam's Club", "price": 45.0, "stock": 74},
    {"id": 176, "item": "Blackberries", "store": "Sam's Club", "price": 44.0, "stock": 54},
    {"id": 177, "item": "Watermelon", "store": "Sam's Club", "price": 65.0, "stock": 32},
    {"id": 178, "item": "Cantaloupe", "store": "Sam's Club", "price": 63.0, "stock": 57},
    {"id": 179, "item": "Honeydew melon", "store": "Sam's Club", "price": 26.0, "stock": 26},
    {"id": 180, "item": "Pineapple", "store": "Sam's Club", "price": 32.0, "stock": 27},
    {"id": 181, "item": "Lemons", "store": "Sam's Club", "price": 3.0, "stock": 9},
    {"id": 182, "item": "Limes", "store": "Sam's Club", "price": 48.0, "stock": 31},
    {"id": 183, "item": "Avocados", "store": "Sam's Club", "price": 9.0, "stock": 95},
    {"id": 184, "item": "Tomatoes", "store": "Sam's Club", "price": 54.0, "stock": 55},
    {"id": 185, "item": "Potatoes", "store": "Sam's Club", "price": 45.0, "stock": 34},
    {"id": 186, "item": "Sweet potatoes", "store": "Sam's Club", "price": 1.0, "stock": 95},
    {"id": 187, "item": "Onions", "store": "Sam's Club", "price": 28.0, "stock": 7},
    {"id": 188, "item": "Garlic bulbs", "store": "Sam's Club", "price": 48.0, "stock": 60},
    {"id": 189, "item": "Bell peppers", "store": "Sam's Club", "price": 15.0, "stock": 55},
    {"id": 190, "item": "Jalapeño peppers", "store": "Sam's Club", "price": 55.0, "stock": 60},
    {"id": 191, "item": "Cucumbers", "store": "Sam's Club", "price": 55.0, "stock": 60},
    {"id": 192, "item": "Zucchini", "store": "Sam's Club", "price": 61.0, "stock": 67},
    {"id": 193, "item": "Yellow squash", "store": "Sam's Club", "price": 15.0, "stock": 13},
    {"id": 194, "item": "Broccoli", "store": "Sam's Club", "price": 54.0, "stock": 80},
    {"id": 195, "item": "Cauliflower", "store": "Sam's Club", "price": 40.0, "stock": 51},
    {"id": 196, "item": "Carrots", "store": "Sam's Club", "price": 58.0, "stock": 72},
    {"id": 197, "item": "Baby carrots", "store": "Sam's Club", "price": 51.0, "stock": 46},
    {"id": 198, "item": "Celery", "store": "Sam's Club", "price": 20.0, "stock": 0},
    {"id": 199, "item": "Lettuce", "store": "Sam's Club", "price": 54.0, "stock": 88},
    {"id": 200, "item": "Spinach", "store": "Sam's Club", "price": 40.0, "stock": 0},
    {"id": 201, "item": "Kale", "store": "Sam's Club", "price": 23.0, "stock": 34},
    {"id": 202, "item": "Cabbage", "store": "Sam's Club", "price": 9.0, "stock": 99},
    {"id": 203, "item": "Chicken", "store": "Sam's Club", "price": 25.0, "stock": 27},
    {"id": 204, "item": "Ground beef", "store": "Sam's Club", "price": 15.0, "stock": 40},
    {"id": 205, "item": "Steak", "store": "Sam's Club", "price": 60.0, "stock": 59},
    {"id": 206, "item": "Pork", "store": "Sam's Club", "price": 54.0, "stock": 9},
    {"id": 207, "item": "Bacon", "store": "Sam's Club", "price": 61.0, "stock": 87},
    {"id": 208, "item": "Breakfast sausage", "store": "Sam's Club", "price": 22.0, "stock": 88},
    {"id": 209, "item": "Hot dogs", "store": "Sam's Club", "price": 50.0, "stock": 65},
    {"id": 210, "item": "Ham", "store": "Sam's Club", "price": 12.0, "stock": 64},
    {"id": 211, "item": "Turkey", "store": "Sam's Club", "price": 4.0, "stock": 34},
    {"id": 212, "item": "Salami", "store": "Sam's Club", "price": 53.0, "stock": 35},
    {"id": 213, "item": "Pepperoni", "store": "Sam's Club", "price": 7.0, "stock": 83},
    {"id": 214, "item": "Frozen chicken nuggets", "store": "Sam's Club", "price": 3.0, "stock": 84},
    {"id": 215, "item": "Frozen chicken tenders", "store": "Sam's Club", "price": 18.0, "stock": 38},
    {"id": 216, "item": "Frozen hamburger patties", "store": "Sam's Club", "price": 19.0, "stock": 30},
    {"id": 217, "item": "Frozen meatballs", "store": "Sam's Club", "price": 67.0, "stock": 94},

    # --- TARGET (IDs 335-384) ---
    {"id": 335, "item": "Bananas", "store": "Target", "price": 66.0, "stock": 46},
    {"id": 336, "item": "Apples", "store": "Target", "price": 6.0, "stock": 11},
    {"id": 337, "item": "Oranges", "store": "Target", "price": 25.0, "stock": 64},
    {"id": 338, "item": "Mandarins", "store": "Target", "price": 45.0, "stock": 70},
    {"id": 339, "item": "Grapes", "store": "Target", "price": 58.0, "stock": 8},
    {"id": 340, "item": "Strawberries", "store": "Target", "price": 44.0, "stock": 40},
    {"id": 341, "item": "Blueberries", "store": "Target", "price": 66.0, "stock": 99},
    {"id": 342, "item": "Raspberries", "store": "Target", "price": 15.0, "stock": 36},
    {"id": 343, "item": "Blackberries", "store": "Target", "price": 5.0, "stock": 86},
    {"id": 344, "item": "Watermelon", "store": "Target", "price": 17.0, "stock": 27},
    {"id": 345, "item": "Cantaloupe", "store": "Target", "price": 38.0, "stock": 36},
    {"id": 346, "item": "Honeydew melon", "store": "Target", "price": 54.0, "stock": 61},
    {"id": 347, "item": "Pineapple", "store": "Target", "price": 27.0, "stock": 80},
    {"id": 348, "item": "Lemons", "store": "Target", "price": 28.0, "stock": 7},
    {"id": 349, "item": "Limes", "store": "Target", "price": 6.0, "stock": 1},
    {"id": 350, "item": "Avocados", "store": "Target", "price": 60.0, "stock": 64},
    {"id": 351, "item": "Tomatoes", "store": "Target", "price": 55.0, "stock": 65},
    {"id": 352, "item": "Potatoes", "store": "Target", "price": 35.0, "stock": 81},
    {"id": 353, "item": "Sweet potatoes", "store": "Target", "price": 14.0, "stock": 60},
    {"id": 354, "item": "Onions", "store": "Target", "price": 12.0, "stock": 19},
    {"id": 355, "item": "Garlic bulbs", "store": "Target", "price": 18.0, "stock": 27},
    {"id": 356, "item": "Bell peppers", "store": "Target", "price": 24.0, "stock": 73},
    {"id": 357, "item": "Jalapeño peppers", "store": "Target", "price": 59.0, "stock": 84},
    {"id": 358, "item": "Cucumbers", "store": "Target", "price": 21.0, "stock": 6},
    {"id": 359, "item": "Zucchini", "store": "Target", "price": 49.0, "stock": 58},
    {"id": 360, "item": "Yellow squash", "store": "Target", "price": 10.0, "stock": 14},
    {"id": 361, "item": "Broccoli", "store": "Target", "price": 26.0, "stock": 84},
    {"id": 362, "item": "Cauliflower", "store": "Target", "price": 11.0, "stock": 84},
    {"id": 363, "item": "Carrots", "store": "Target", "price": 54.0, "stock": 38},
    {"id": 364, "item": "Baby carrots", "store": "Target", "price": 19.0, "stock": 0},
    {"id": 365, "item": "Celery", "store": "Target", "price": 39.0, "stock": 54},
    {"id": 366, "item": "Lettuce", "store": "Target", "price": 9.0, "stock": 45},
    {"id": 367, "item": "Spinach", "store": "Target", "price": 21.0, "stock": 84},
    {"id": 368, "item": "Kale", "store": "Target", "price": 64.0, "stock": 99},
    {"id": 369, "item": "Cabbage", "store": "Target", "price": 66.0, "stock": 54},
    {"id": 370, "item": "Chicken", "store": "Target", "price": 7.0, "stock": 100},
    {"id": 371, "item": "Ground beef", "store": "Target", "price": 41.0, "stock": 70},
    {"id": 372, "item": "Steak", "store": "Target", "price": 23.0, "stock": 36},
    {"id": 373, "item": "Pork", "store": "Target", "price": 35.0, "stock": 71},
    {"id": 374, "item": "Bacon", "store": "Target", "price": 45.0, "stock": 12},
    {"id": 375, "item": "Breakfast sausage", "store": "Target", "price": 26.0, "stock": 28},
    {"id": 376, "item": "Hot dogs", "store": "Target", "price": 56.0, "stock": 90},
    {"id": 377, "item": "Ham", "store": "Target", "price": 15.0, "stock": 72},
    {"id": 378, "item": "Turkey", "store": "Target", "price": 32.0, "stock": 26},
    {"id": 379, "item": "Salami", "store": "Target", "price": 54.0, "stock": 0},
    {"id": 380, "item": "Pepperoni", "store": "Target", "price": 28.0, "stock": 74},
    {"id": 381, "item": "Frozen chicken nuggets", "store": "Target", "price": 39.0, "stock": 78},
    {"id": 382, "item": "Frozen chicken tenders", "store": "Target", "price": 36.0, "stock": 94},
    {"id": 383, "item": "Frozen hamburger patties", "store": "Target", "price": 44.0, "stock": 54},
    {"id": 384, "item": "Frozen meatballs", "store": "Target", "price": 19.0, "stock": 93},

    # --- WALMART (IDs 502-551) ---
    {"id": 502, "item": "Bananas", "store": "Walmart", "price": 55.0, "stock": 44},
    {"id": 503, "item": "Apples", "store": "Walmart", "price": 41.0, "stock": 44},
    {"id": 504, "item": "Oranges", "store": "Walmart", "price": 45.0, "stock": 32},
    {"id": 505, "item": "Mandarins", "store": "Walmart", "price": 12.0, "stock": 35},
    {"id": 506, "item": "Grapes", "store": "Walmart", "price": 39.0, "stock": 61},
    {"id": 507, "item": "Strawberries", "store": "Walmart", "price": 45.0, "stock": 15},
    {"id": 508, "item": "Blueberries", "store": "Walmart", "price": 56.0, "stock": 96},
    {"id": 509, "item": "Raspberries", "store": "Walmart", "price": 15.0, "stock": 67},
    {"id": 510, "item": "Blackberries", "store": "Walmart", "price": 39.0, "stock": 12},
    {"id": 511, "item": "Watermelon", "store": "Walmart", "price": 20.0, "stock": 69},
    {"id": 512, "item": "Cantaloupe", "store": "Walmart", "price": 57.0, "stock": 13},
    {"id": 513, "item": "Honeydew melon", "store": "Walmart", "price": 33.0, "stock": 28},
    {"id": 514, "item": "Pineapple", "store": "Walmart", "price": 66.0, "stock": 100},
    {"id": 515, "item": "Lemons", "store": "Walmart", "price": 45.0, "stock": 57},
    {"id": 516, "item": "Limes", "store": "Walmart", "price": 12.0, "stock": 34},
    {"id": 517, "item": "Avocados", "store": "Walmart", "price": 60.0, "stock": 19},
    {"id": 518, "item": "Tomatoes", "store": "Walmart", "price": 12.0, "stock": 21},
    {"id": 519, "item": "Potatoes", "store": "Walmart", "price": 35.0, "stock": 42},
    {"id": 520, "item": "Sweet potatoes", "store": "Walmart", "price": 56.0, "stock": 69},
    {"id": 521, "item": "Onions", "store": "Walmart", "price": 45.0, "stock": 28},
    {"id": 522, "item": "Garlic bulbs", "store": "Walmart", "price": 61.0, "stock": 44},
    {"id": 523, "item": "Bell peppers", "store": "Walmart", "price": 54.0, "stock": 93},
    {"id": 524, "item": "Jalapeño peppers", "store": "Walmart", "price": 21.0, "stock": 64},
    {"id": 525, "item": "Cucumbers", "store": "Walmart", "price": 50.0, "stock": 27},
    {"id": 526, "item": "Zucchini", "store": "Walmart", "price": 54.0, "stock": 43},
    {"id": 527, "item": "Yellow squash", "store": "Walmart", "price": 31.0, "stock": 19},
    {"id": 528, "item": "Broccoli", "store": "Walmart", "price": 36.0, "stock": 41},
    {"id": 529, "item": "Cauliflower", "store": "Walmart", "price": 58.0, "stock": 6},
    {"id": 530, "item": "Carrots", "store": "Walmart", "price": 43.0, "stock": 40},
    {"id": 531, "item": "Baby carrots", "store": "Walmart", "price": 41.0, "stock": 58},
    {"id": 532, "item": "Celery", "store": "Walmart", "price": 3.0, "stock": 55},
    {"id": 533, "item": "Lettuce", "store": "Walmart", "price": 25.0, "stock": 60},
    {"id": 534, "item": "Spinach", "store": "Walmart", "price": 42.0, "stock": 25},
    {"id": 535, "item": "Kale", "store": "Walmart", "price": 41.0, "stock": 55},
    {"id": 536, "item": "Cabbage", "store": "Walmart", "price": 60.0, "stock": 82},
    {"id": 537, "item": "Chicken", "store": "Walmart", "price": 6.0, "stock": 72},
    {"id": 538, "item": "Ground beef", "store": "Walmart", "price": 26.0, "stock": 83},
    {"id": 539, "item": "Steak", "store": "Walmart", "price": 15.0, "stock": 40},
    {"id": 540, "item": "Pork", "store": "Walmart", "price": 51.0, "stock": 84},
    {"id": 541, "item": "Bacon", "store": "Walmart", "price": 13.0, "stock": 88},
    {"id": 542, "item": "Breakfast sausage", "store": "Walmart", "price": 42.0, "stock": 9},
    {"id": 543, "item": "Hot dogs", "store": "Walmart", "price": 41.0, "stock": 0},
    {"id": 544, "item": "Ham", "store": "Walmart", "price": 60.0, "stock": 72},
    {"id": 545, "item": "Turkey", "store": "Walmart", "price": 32.0, "stock": 88},
    {"id": 546, "item": "Salami", "store": "Walmart", "price": 50.0, "stock": 15},
    {"id": 547, "item": "Pepperoni", "store": "Walmart", "price": 37.0, "stock": 20},
    {"id": 548, "item": "Frozen chicken nuggets", "store": "Walmart", "price": 46.0, "stock": 34},
    {"id": 549, "item": "Frozen chicken tenders", "store": "Walmart", "price": 13.0, "stock": 27},
    {"id": 550, "item": "Frozen hamburger patties", "store": "Walmart", "price": 40.0, "stock": 0},
    {"id": 551, "item": "Bread", "store": "Walmart", "price": 5.0, "stock": 3},
    {"id": 553, "item": "Bread", "store": "Target", "price": 7.0, "stock": 4},
    {"id": 554, "item": "Bread", "store": "Meijer", "price": 6.0, "stock": 10},
    {"id": 555, "item": "Eggs", "store": "Walmart", "price": 3.0, "stock": 9},
    {"id": 556, "item": "Eggs", "store": "Walmart", "price": 5.0, "stock": 20},
    {"id": 557, "item": "Eggs", "store": "Meijer", "price": 3.0, "stock": 18},
    {"id": 558, "item": "Milk", "store": "Walmart", "price": 5.0, "stock": 33},
    {"id": 559, "item": "Milk", "store": "Sam's Club", "price": 2.0, "stock": 13},
    {"id": 560, "item": "Milk", "store": "Target", "price": 5.0, "stock": 10},
]


MOCK_PRODUCTS = [
    {
        "id": 1,
        "item": "Milk",
        "store": "Kroger",
        "price": 3.49,
        "stock": 12
    },
    {
        "id": 2,
        "item": "Milk",
        "store": "Walmart",
        "price": 3.19,
        "stock": 20
    },
    {
        "id": 3,
        "item": "Bread",
        "store": "Target",
        "price": 2.29,
        "stock": 8
    }
]

@app.route("/api/search")
def search():
    query = request.args.get("q", "").lower()

    results = [
        p for p in MOCK_PRODUCTS
        if query == p["item"].lower()
    ]

    return jsonify(results)

# TODO: make methods that show results based on proximity to location and price

@app.route("/api/search_lowest")
def search_lowest():
    query = request.args.get("q", "").lower()
    
    results = [
        p for p in BACKUP_INVENTORY
        if query == p["item"].lower()
    ]
    
    sorted_products = sorted(results, key=lambda x: (x["price"], -x["stock"]))
    return jsonify(sorted_products)

if __name__ == "__main__":
    app.run(debug=True)
